# Generated by Django 3.2.10 on 2021-12-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl', models.TextField(max_length=1000)),
                ('eng', models.TextField(max_length=1000)),
            ],
        ),
    ]
