# Generated by Django 3.2.10 on 2021-12-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_ranking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranking',
            old_name='diff',
            new_name='lvl',
        ),
    ]
